language: node_js
node_js:
  - "10"
  - "11"
sudo: required
before_script:
  - npm install -g @angular/cli
script:
  - npm run build:server
  - npm run build:client
  - npm run test:server
  - npm run test:client